### ISSUE TITLE
would be nice to have an option to have a print list with units/weapon stats/rules.

### ISSUE THREAD

**Issue by rafparis** [JWTC2200/legionbuilder#5]
like in battlescribe, some sort of unit cards

**Comment by rafparis** [comment]
<img width="794" alt="image" src="https://github.com/JWTC2200/legionbuilder/assets/1112513/a6c23780-886a-4db9-8c25-7ae18cd0e2fe">

**Comment by JWTC2200** [comment]
I'm not likely to do this for a while. 
I don't have the rulebook yet so can't get the exact text for tooltips or references etc...
Also a bit nervous as GW sell a set of cards? I think its sold out but still rather not step on that until a little bit after launch.

**Comment by rafparis** [comment]
the screen above is from battlescribe, so i dont think you will have any problem :) And you already have the base for it, in the form of the units in the reference. Just need to add the choice of weapons, but even with everything it is ok. And the rules can be only keywords for now,

**Comment by The4D6** [comment]
> the screen above is from battlescribe, so i dont think you will have any problem :) And you already have the base for it, in the form of the units in the reference. Just need to add the choice of weapons, but even with everything it is ok. And the rules can be only keywords for now,

As someone who is a lead dev on the BattleScribe Heresy team, I can tell you for a fact that "just because we do it doesn't mean it's ok"

BattleScribe as a system exists by the grace of James Workshop, the more systems out there that copy/publish/work with their rules without explicit permission, the more likely they are to take notice and do something about it.
